dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'

dotenv: .env
networks:
  default: development
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    verify: True
    key_hash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
  development:
    key_hash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
    verify: False
wallets: 
  from_key: ${PRIVATE_KEY}